@startuml

(*) --> "espera ()"
if " while recursos<1" then
--> [ true ] "wait ()"
else
--> [ false ] "recursos --"
--> (*)
(*) --> "libera ()"
--> "recursos ++"
--> "notifyAll()"
--> (*)
"wait ()" -->[ notifyAll()                ] "espera ()"


@enduml

@startuml
class Estado
@enduml