@startuml

'AssemblerModel -> Line : start ()
'Line --> AssemblerModel : station_spot
'
'AssemblerModel -> Station : to work (Line)
'Station -> Line : works on


AssemblerView -> AssemblerController : creates
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response
@enduml